version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pedido_app
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pedido_dbhost:5432/pedido_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8080
      - MS_PAGAMENTO_URL=http://pagamento_app:8083
      - MS_PRODUCAO_URL=http://producao_app:8084

  db:
    image: postgres:15
    restart: always
    container_name: pedido_dbhost
    environment:
      - POSTGRES_DB=pedido_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"