apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pedido
  labels:
    name: ms-pedido
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-pedido
  template:
    metadata:
      labels:
        app: ms-pedido
    spec:
      containers:
      - name: ms-pedido
        image: pabloldias/soat1-grupo18-ms-pedido:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "2000m"
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://fiap-ms-pedido.cr0dnn5xiohv.us-east-1.rds.amazonaws.com:5432/fiap_ms_pedido
        - name: SPRING_DATASOURCE_USERNAME
          value: dbuser
        - name: SPRING_DATASOURCE_PASSWORD
          value: dbpassword
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: MS_PAGAMENTO_URL
          value: http://ms-pagamento.ms-pagamento
        - name: MS_PRODUCAO_URL
          value: http://ms-producao.ms-producao
        ports:
        - containerPort: 8080
