name: Build and test

on:
  pull_request:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  microservices-deploy:
    uses: soat1-grupo18/fase3-reusable-github-workflows/.github/workflows/microservices-deploy.yml@main
    with:
      microservice-id: soat1-grupo18-ms-pedido
    secrets: inherit

  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    needs:
      - microservices-deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.3'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::289389227463:role/github-org-soat1-grupo18
          aws-region: us-east-1

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name fiap-cluster

      - name: Deploy
        uses: Azure/k8s-deploy@v4
        with:
          namespace: default
          manifests: |
              kubernetes/
          images: '${{ secrets.DOCKER_HUB_USER }}/soat1-grupo18-ms-pedido:${{ github.sha }}'