name: Build and test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  infrastructure:
    uses: soat1-grupo18/fase3-reusable-github-workflows/.github/workflows/aws-terraform.yml@main
    with:
      aws-region: us-east-1
      terraform-directory-path: infrastructure
      terraform-version: 1.7.0
    secrets: inherit

  microservices-deploy:
    uses: soat1-grupo18/fase3-reusable-github-workflows/.github/workflows/microservices-deploy.yml@main
    with:
      microservice-id: soat1-grupo18-ms-pedido
    secrets: inherit
